// <auto-generated />
using FluentBlazorEcommerce.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluentBlazorEcommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240419172934_InititalMigration")]
    partial class InititalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("FluentBlazorEcommerce.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptops and Notebooks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smartphones and Mobile Devices"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wearable Technology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming Consoles and Accessories"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Computer Accessories and Peripherals"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Monitors and Displays"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Graphics Cards and Video Devices"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Keyboards and Mice"
                        });
                });

            modelBuilder.Entity("FluentBlazorEcommerce.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("FluentBlazorEcommerce.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop for gaming and productivity.",
                            Name = "High-Performance Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Latest smartphone with advanced features and high-resolution camera.",
                            Name = "Latest Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fitness tracker with heart rate monitor and GPS functionality.",
                            Name = "Fitness Smartwatch",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Next-gen gaming console with immersive gaming experience.",
                            Name = "Next-Gen Gaming Console",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Noise-canceling wireless headphones with long battery life.",
                            Name = "Noise-Canceling Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ultra-high-definition monitor for crystal-clear visuals.",
                            Name = "Ultra-HD Monitor",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Powerful graphics card for smooth gaming and video rendering.",
                            Name = "Powerful Graphics Card",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Mechanical keyboard with customizable RGB lighting.",
                            Name = "Mechanical Keyboard",
                            Price = 129.99m
                        });
                });

            modelBuilder.Entity("FluentBlazorEcommerce.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FluentBlazorEcommerce.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "saetea24.com",
                            Username = "Saeko"
                        },
                        new
                        {
                            Id = 2,
                            Email = "renarakawa42.com",
                            Username = "Ren"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
